### ISSUE TITLE
3.0 Canvas -- Transition drawing tasks

### ISSUE THREAD

**Issue by bmomberger-bitovi** [StackStorm/st2flow#165]
This is a breakout from the canvas work from #149 , providing greater detail.

- [x] Fix SVG path creation algorithm for transitions (3 days)
- [x] Make transitions auto-avoid crossing task boxes (2 days)
- Transition crossing tasks
  - [ ] Make transitions cross minimally (2 days)
  - [ ] crossing transitions should "bump" when cross can't be avoided. (0.5 day)
