### ISSUE TITLE
3.0dev Master Tracking Issue

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2flow#186]
This issue will track more specific issues identified during pre-3.0 release testing.

## High Priority - ship blockers

- [x] #185 Unable to edit new workflow - https://github.com/StackStorm/st2flow/pull/192
- [x] #180 No option to edit existing Orquesta/~~Action-Chain~~ workflow - https://github.com/StackStorm/st2web/pull/626, https://github.com/StackStorm/st2web/pull/627, https://github.com/StackStorm/bwc-ui/pull/56, https://github.com/StackStorm/bwc-ui/pull/57
- [x] #190 Can't re-open workflow after saving it  - https://github.com/StackStorm/st2flow/pull/191
- [x] #193 Flow goes into infinite pack icon loading loop if pack doesn't contain an icon - https://github.com/StackStorm/st2flow/issues/193
- [x] #198 Provide a better indication of "Workflow save" operation success / failure - https://github.com/StackStorm/st2flow/pull/200

## Medium Priority

- [x] #181 Header Colors are wrong - should be easy fix - ship blocker - https://github.com/StackStorm/st2flow/pull/195
- [x] #182 Logo should be used in header - should be easy fix - ship blocker - https://github.com/StackStorm/st2flow/pull/195

## Low Priority

- [ ] #184 Console Error - window.controllers/Controllers is deprecated - probably hard to fix. Not blocker.
- [ ] #187 - picker for transition arrow color. Not blocker.
- [ ] #188 - drop-down indicator looks ugly. Not blocker
